"""
Created on Sat June 5 21:25:32 2021
@author: Vidya Venkatesan (vidyav1@uci.edu)

Project description: This code is a python version of ice_gcm.pro which calculates the albedo from stellar 
spectrum and spectrum of reflectance.
Note: any spectrum file can be used along with any reflectance spectrum provided the minGrid and maxGrid parameters
are changed to reflect the appropriate units. Units are not important (as long as the wavelength units are the same for
each file) for the final albedo calculations since it is normalized by both the wavelength and the stellar spectrum.
This 6-band calculator can be used for models like 1-D EBMs and ExoCAM.

Required Inputs:
    stellarfile = file containing two columns:
                  1 - wavelength, microns
                  2 - flux, in any units (this is normalized for the albedo calculation)
    albedofile  = file containing three columns (as generated by the USGS):
                  1 - wavelength, in microns
                  2 - reflectance at that wavelength (0 - 1)
                  3 - error, if any
"""


# Importing libraries
import numpy as np
import scipy.interpolate as interpol
import matplotlib.pyplot as plt

stel_convert_wavl = 1.0e6

# Reading in the stellar file
with open('sun.txt', 'r') as f:
    lines = f.readlines()
    # If you have header lines, consider skipping them with: for _ in range(3): next(f)
    lamda = [float(line.split()[0]) * 10**6 for line in lines] 
    flux = [float(line.split()[1]) for line in lines]
print("Stellar wavelengths (μm):", lamda)

# Reading in the albedo file for surface
with open('croyoconite.txt', 'r') as f:
    lines = f.readlines()
    wave = [float(line.split()[0]) for line in lines]
    albedo = [float(line.split()[1]) for line in lines]

# Determine the overlapping wavelength range between the stellar and albedo data
start_g = max(np.min(wave), np.min(lamda))
end_g = min(np.max(wave), np.max(lamda))

# Set up the wavelength grid for interpolation
ngrid = 10000
n = np.arange(ngrid)
k = end_g - start_g
wavelengthgrid = start_g + k * n / (ngrid - 1)
dlamda = (np.max(wavelengthgrid) - np.min(wavelengthgrid)) / (len(wavelengthgrid) - 1)

# Interpolate the stellar flux and albedo onto the common wavelength grid
stellarInterpolate4 = np.interp(wavelengthgrid, lamda, flux)
albedoInterpolate = interpol.CubicSpline(wave, albedo)(wavelengthgrid)

# Normalize the stellar flux
flux4 = stellarInterpolate4 / np.max(stellarInterpolate4)

# Scale the stellar flux using a normalization factor (e.g., Snorm = 1360)
Snorm = 1360
total_sed4 = sum(stellarInterpolate4 * dlamda)
ScaleFac = Snorm / total_sed4
new_flux4 = stellarInterpolate4 * ScaleFac

# Define the two bands based on a 0.7 μm cutoff:
# - Band 1: wavelengths < 0.7 μm
# - Band 2: wavelengths >= 0.7 μm
indices_lower = np.where(wavelengthgrid < 0.7)
indices_upper = np.where(wavelengthgrid >= 0.7)

# Calculate albedo for the lower band (0 to 0.7 μm)
albedo_sed_lower = albedoInterpolate[indices_lower] * new_flux4[indices_lower] * dlamda
total_albedo_sed_lower = sum(albedo_sed_lower)
total_sed_lower = sum(new_flux4[indices_lower] * dlamda)
albedo_lower = total_albedo_sed_lower / total_sed_lower if total_sed_lower != 0 else 0

# Calculate albedo for the upper band (>= 0.7 μm)
albedo_sed_upper = albedoInterpolate[indices_upper] * new_flux4[indices_upper] * dlamda
total_albedo_sed_upper = sum(albedo_sed_upper)
total_sed_upper = sum(new_flux4[indices_upper] * dlamda)
albedo_upper = total_albedo_sed_upper / total_sed_upper if total_sed_upper != 0 else 0

# Optionally, calculate total albedo over the full range
indices_all = np.where((wavelengthgrid >= start_g) & (wavelengthgrid <= end_g))
albedo_sed_all = albedoInterpolate[indices_all] * new_flux4[indices_all] * dlamda
total_albedo_sed_all = sum(albedo_sed_all)
total_sed_all = sum(new_flux4[indices_all] * dlamda)
albedo_all = total_albedo_sed_all / total_sed_all if total_sed_all != 0 else 0

# Print the albedo results
print(f"Albedo (0 to 0.7 μm): {albedo_lower:.6f}")
print(f"Albedo (>= 0.7 μm): {albedo_upper:.6f}")
print(f"Total Albedo ({start_g:.2f} - {end_g:.2f} μm): {albedo_all:.6f}")
